version: '3'

services:
  person-service:
    image: image3
    ports:
      - "8080:8080"
    environment:
      - DB_IP=person-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1969
      - DB_NAME=person-db
    networks:
      demo_net:
        aliases:
          - person-service

  person-db:
    image: postgres
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_DB=person-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1969
    volumes:
      - person-db-data:/var/lib/postgresql/data  # Mount volume for database data
    networks:
      demo_net:

networks:
  demo_net:
    external: true

volumes:
  person-db-data:
